ImageGallery/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos
  resources :galleries
  resources :errors
  match "galleries/:id/slideshow", to: 'galleries#slideshow', via: [:get]
  root to: 'galleries#index'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

ImageGallery/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ImageGallery/app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :galleries_photos
  has_many :photos, through: :galleries_photos
  validates :title, :linked_photo_ids, presence: true
end

ImageGallery/app/models/gallery_photo.rb
class GalleryPhoto < ApplicationRecord
  belongs_to :photo
  belongs_to :gallery
end

ImageGallery/app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image, :dependent => :destroy
  has_many :galleries_photos
  has_many :galleries, through: :galleries_photos
end

ImageGallery/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

ImageGallery/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ImageGallery/app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

ImageGallery/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :slideshow]

  # GET /galleries or /galleries.json
  # GET /index?order=[title_asc, title_desc, users_asc]
  def index
    @galleries = Gallery.all    
    @users = []
    @galleries.each do |user|
      @users << User.find(user.user_id)
    end
    if params[:order] == 'title_asc'
      @galleries = @galleries.order('title ASC')
    elsif params[:order] == 'title_desc'
      @galleries = @galleries.order('title DESC')
    elsif params[:order] == 'users'
      @galleries = @galleries.order('user_id ASC')
    end

  end

  # GET /galleries/1 or /galleries/1.json
  def show
    @list = (Gallery.find(params[:id])).linked_photo_ids
    @photos = Photo.find(@list)
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
    @all_photos = Photo.where("user_id = #{current_user.id}")
  end

  # GET /galleries/1/edit
  def edit
  end

  # GET /galleries/1/slideshow
  def slideshow
    @gallery_user_id = Gallery.find(params[:id]).user_id
    @list = (Gallery.find(params[:id])).linked_photo_ids
    @photos = Photo.find(@list)
  end

  # POST /galleries or /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user_id = current_user.id
    
    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: "Gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: "Gallery was successfully updated." }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1 or /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: "Gallery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
      @gallery_id = params[:id]
      @gallery_user_id = Gallery.find(params[:id]).user_id
      @photos = Photo.where("user_id = #{@gallery_user_id}")
      if user_signed_in?
        @all_photos = Photo.where("user_id = #{current_user.id}")
      end
    end

    # Only allow a list of trusted parameters through.
    def gallery_params
      params.require(:gallery).permit(:user_id, :title, :linked_photo_ids => [])
    end
end

ImageGallery/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
    @thumbnails = []
    i = 0
    @photos.each do |photo|
      @thumbnails[i] = photo.image.variant(resize_to_fit: [100, 100]).processed
      i += 1
    end
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:user_id, :image)
    end
end

ImageGallery/app/helpers/application_helper.rb
module ApplicationHelper
end

ImageGallery/app/helpers/errors_helper.rb
module ErrorsHelper
end

ImageGallery/app/helpers/galleries_helper.rb
module GalleriesHelper
end

ImageGallery/app/helpers/photos_helper.rb
module PhotosHelper
end

ImageGallery/app/views/galleries/_form.html.erb
<%= simple_form_for(@gallery, local: true) do |f| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>
      <ul>
        <% gallery.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>

  <div class="field" id="gallery_title">
    <h3>Title: <%= f.input_field :title, :required => true %></h3>
  </div>

  <table id="photo_table">
  <% if defined? @all_photos %>
    <tr>
      <th>Image:</th>
      <% @all_photos.each do |photo| %>
        <td><%= image_tag photo.image.variant(resize_to_fit:[100,100]).processed %></td>
      <% end %>
    </tr>
    <tr>
      <th>ID:</th>
      <% @all_photos.each do |photo| %>
        <td><%= photo.id %></td>
      <% end %>
    </tr>
    </table>
    <div class="field" id="select_photos">
      <h3>Select Images:</h3>
      <%= f.select :linked_photo_ids, @all_photos.ids, {:placeholder => false, include_hidden: false, :required => true}, {:multiple => true, :value => :id} %>
      <p>*For Windows hold <code>CTRL</code>, for Mac hold <code>CMD</code> to select multiple images</p>
  </div>
  <% end %>

  <div class="actions" >
    <%= f.button :submit, class:"submit_button" %>
  </div>
<% end %>

ImageGallery/app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

ImageGallery/app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galleries</h1>

<p>
  <h3>Sort by:</h3>
  <%= link_to "Title Asc", galleries_path(order: 'title_asc') %>
  <%= link_to "Title Desc", galleries_path(order: 'title_desc') %>
  <%= link_to "Users", galleries_path(order: 'users') %>
<p>


<table>
  <thead>
    <tr>
      <th>Title:</th>
      <th>Created By:</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% i = 0 %>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.title %></td>
        <td><%= @users[i].email %></td>
        <% i += 1 %>
        <td><%= link_to 'View', gallery %></td>
        <% if user_signed_in? %>
          <% if gallery.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
            <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

ImageGallery/app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Back', galleries_path %>

ImageGallery/app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @gallery.title %></h1>

<h2>Images:</h2>
<% @photos.each do |photo| %>
  <% if photo.image.attached? %>
    <%= link_to(image_tag(photo.image.variant(resize_to_fit: [200,200]).processed), photo.image_attachment, class:"image_link") %>
  <% end %>
<% end %>


<p><%= link_to "Slideshow", "#{@gallery.id}/slideshow" %></p>
<p><%= link_to 'Back', galleries_path %></p>

ImageGallery/app/views/galleries/slideshow.erb
<p id="notice"><%= notice %></p>

<% @photos.each do |photo| %>
  <% if photo.image.attached? %>
    <%= image_tag(photo.image) %>
  <% end %>
<% end %>

<br>
<%= link_to 'Back', galleries_path %>

ImageGallery/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageGallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class = "navbar">
      <li>
        <%= link_to :root, title: "Go to the home page" do %>Home<% end %>
      </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to :new_gallery, title: "New Gallery page" do %>New Gallery<% end %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li>
          <%= link_to :new_photo, title: "New Photo page" do %>Upload Photo<% end %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li>
          <%= link_to :photos, title: "Manage Photo page" do %>Manage My Photos<% end %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li>
          <%= link_to :destroy_user_session, method: :delete, title: "Log out of the system" do %>Log Out<% end %>
        </li>
      <% end %>
      <% if !user_signed_in? %>
        <li>
          <%= link_to :photos, title: "Sign In" do %> Login <% end %>
        </li>
      <% end %>
    </ul>
    <%= yield %>

    <footer>
      <p><strong>Daniel Tebbutt &copy 2021 </strong><%= link_to 'https://gitlab.com/d-tebbs/imagegallery' do %>GitLab<% end %></p>
    </footer>
  </body>
</html>

ImageGallery/app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id %> 

  <div class="field">
    <h3>Pick Image:</h3>
    <%= form.file_field :image, :required => true, class:"submit_button" %>
  </div>

  

  <div class="actions">
    <%= form.submit :class => "submit_button" %>
  </div>
<% end %>

ImageGallery/app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

ImageGallery/app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
      <% if user_signed_in? %>
        <% if photo.user_id == current_user.id %>  
          <td><% if photo.image.attached? %>
            <%= link_to(image_tag(photo.image.variant(resize_to_fit: [100,100]).processed), photo.image_attachment, class:"image_link") %>
          <% end %></td>
          <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
          <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

ImageGallery/app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

ImageGallery/app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo ID:</strong> <%= @photo.id %> | <strong>User ID:</strong> <%= @photo.user_id %>
</p>
<p>
  <strong>Image:</strong>
  <br>
  
  <%= image_tag @photo.image %>
  
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>